name: Hexo Blog CI

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0   

      - name: Setup Node # 安装 Node 环境
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Hexo Generate         # 安装 Hexo 依赖并且生成静态文件
        run: |
          rm -f .yarnclean
          yarn --frozen-lockfile --ignore-engines --ignore-optional --non-interactive --silent --ignore-scripts --production=false
          rm -rf ./public
          yarn run hexo clean
          yarn run hexo generate

      - name: Hexo Deploy           # 部署步骤，这里以 hexo deploy 为例
        env:
          SSH_PRIVATE: ${{ secrets.DEPLOY_KEY }}
          GIT_NAME: "wubh2012"
          GIT_EMAIL: "wubh2012@163.com"
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "$GIT_NAME"
          git config --global user.email "$GIT_EMAIL"
          yarn run hexo deploy
          
